# Generated by Django 3.1 on 2022-08-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=50)),
                ('user_contact', models.CharField(max_length=12)),
                ('job_title', models.CharField(max_length=20)),
                ('job_desription', models.CharField(max_length=300)),
                ('publish_date', models.DateField()),
                ('schedule_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_job_done', models.CharField(max_length=300)),
                ('price_charge', models.IntegerField()),
                ('job_dd', models.DateTimeField()),
            ],
        ),
    ]
