# Generated by Django 4.0 on 2022-08-15 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just', '0002_alter_price_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('Qid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
