# Generated by Django 3.1 on 2022-08-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just', '0003_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='date',
            field=models.DateTimeField(default=True),
        ),
        migrations.AlterField(
            model_name='price',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
