# Generated by Django 4.0 on 2022-08-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('just', '0004_auto_20220816_0635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='date',
        ),
        migrations.AddField(
            model_name='form',
            name='file',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AlterField(
            model_name='price',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
