# Generated by Django 4.0 on 2022-08-18 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('just', '0006_alter_form_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='file',
        ),
    ]
